version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: dev_jobs_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: job_scrapper
    networks:
      - dev_jobs_network

  # Job Scrapper
  scrapper:
    build: .
    container_name: dev_jobs_scrapper
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
      - WEBHOOK_URL=${WEBHOOK_URL}
      - LOG_WEBHOOK_URL=${LOG_WEBHOOK_URL}
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
      - GOOGLE_CHROME_BIN=/usr/bin/chromium
    volumes:
      - ./srcs:/app/srcs
    networks:
      - dev_jobs_network

  # Dashboard Web
  dashboard:
    build: ./dashboard
    container_name: dev_jobs_dashboard
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    networks:
      - dev_jobs_network

volumes:
  mongo_data:

networks:
  dev_jobs_network:
    driver: bridge
